export type Suit = '♠' | '♥' | '♦' | '♣';
export type Rank = 'A' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | 'J' | 'Q' | 'K';
export type Card = { id: string; suit: Suit; rank: Rank; faceUp: boolean; zeroed?: boolean };
export type Grid = (Card | null)[][];
export type PlayerIdentity = { userId: string; displayName?: string; name?: string; avatarInitial?: string };
export type Player = { id: string; userId: string; name: string; avatarInitial?: string; grid: Grid; score: number; peekFlips: number; connected?: boolean };
export type GameState = {
  id: string; players: Player[]; currentPlayerIndex: number; drawPile: Card[]; discardPile: Card[];
  phase: 'peek' | 'turn' | 'roundEnd'; topDiscard: Card | null; turnEndsAt?: number; peekTurnIndex?: number;
  peekEndsAt?: number; mustDrawOnlyForPlayerIndex?: number; round?: number; totalRounds?: number; totals?: number[];
  sweepActive?: boolean; sweepStarterIndex?: number | null; completed?: boolean; revision?: number; lastRoundScores?: number[];
};
export const ROWS: number;
export const COLS: number;
export const TURN_DURATION: number;
export const PEEK_DURATION: number;
export const MAX_PLAYERS: number;
export const MIN_PLAYERS: number;
export function makeId(prefix?: string): string;
export function sanitizePlayerIdentity(user: { userId: string; displayName?: string }): PlayerIdentity;
export function createDeck(): Card[];
export function shuffle<T>(arr: T[]): T[];
export function cardValue(card: Card | null): number;
export function initGrid(): Grid;
export function cloneState<T>(state: T): T;
export function scoreGrid(grid: Grid): number;
export function createGameState(playerIdentities: PlayerIdentity[], options?: { round?: number; totalRounds?: number; totals?: number[] }): GameState;
export function dealLocal(players: number): GameState;
export function startTurns(state: GameState): GameState;
export function advancePeek(state: GameState): GameState;
export function flipForPeek(state: GameState, playerIndex: number, r: number, c: number): { state: GameState; error?: string };
export function autoCompleteCurrentPeek(state: GameState): GameState;
export function drawFromDeck(state: GameState): { state: GameState; drawn: Card | null; error?: string };
export function takeDiscard(state: GameState): { state: GameState; drawn: Card | null; error?: string };
export function replaceGridCard(state: GameState, playerIndex: number, r: number, c: number, newCard: Card): { state: GameState; error?: string };
export function discardDrawn(state: GameState, playerIndex: number, card: Card): { state: GameState; error?: string };
export function resolveExpiredTimers(state: GameState): GameState;
export function isRoundOver(state: GameState): boolean;
export function pickTarget(grid: Grid, incoming: Card): { r: number; c: number };
export function publicGameState(state: GameState, viewerUserId?: string | null): GameState;
